name              'consul_fx'
maintainer        'fxinnovation'
maintainer_email  'cloudsquad@fxinnovation.com'
license           'MIT'
description       'Provides a resource for (un)installing consul'
version           '0.1.0'
source_url        'https://bitbucket.org/fxadmin/public-common-cookbook-consul_fx'
issues_url        'https://bitbucket.org/fxadmin/public-common-cookbook-consul_fx/issues'
chef_version      '>=12.14' if respond_to?(:chef_version)
depends           'nssm'
depends           'unzip_fx'
supports          'debian', '>= 8'
supports          'ubuntu', '>= 14.04'
supports          'redhat', '>= 6.0'
supports          'centos', '>= 6.0'
